# Generated by Django 3.1.1 on 2020-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywall_bypass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
