# Generated by Django 3.1.1 on 2020-09-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paywall_bypass', '0002_auto_20200926_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
